version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234abcd
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network

  # Mongo-Admin (MongoDB UI) service
  mongo-admin:
    image: mongo-express:latest
    container_name: mongo-admin
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:1234abcd@mongodb:27017/?authSource=admin&ssl=false
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234abcd
      ME_CONFIG_BASICAUTH_USERNAME: root   # Username for Mongo-Express login
      ME_CONFIG_BASICAUTH_PASSWORD: 1234abcd  # Password for Mongo-Express login
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
